name: Changelog
on:
  release:
    types: [published]
jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Send to Noticeable
        uses: nexmo/release-to-noticeable-action@v1
        env:
          NOTICEABLE_API_KEY: "ZIRHNh2UVFjkMKYCQ8c6"
          NOTICEABLE_PROJECT_ID: "sZtjHlGLyuytOuwaOnk4"
        with:
          draft: true
          tags: PHP,Server SDK
